from __future__ import annotations

import json
import os
import base64
import re
import sys
from pathlib import Path

from flask import Flask, Response, request, send_from_directory

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# Vercel serverless functions can write to /tmp, not to the deployed project
# directory. Local tests use results/vercel_tmp so the normal local dashboard
# continues to use results/.
if os.environ.get("VERCEL"):
    os.environ.setdefault("TA_MOACO_RESULTS_DIR", "/tmp/results")
else:
    os.environ.setdefault("TA_MOACO_RESULTS_DIR", str(ROOT / "results" / "vercel_tmp"))

from local_dashboard import RESULTS_ROOT, controls, html_page, run_simulation_html


app = Flask(__name__)


def _result_file_from_url(url_path: str) -> Path:
    """Map a /results/... URL generated by local_dashboard.py to disk."""

    relative = url_path.split("?", 1)[0]
    if relative.startswith("/results/"):
        relative = relative[len("/results/") :]
    return Path(RESULTS_ROOT) / relative


def _embed_generated_assets(html: str) -> str:
    """Embed generated PNG/report assets for Vercel serverless reliability.

    The local dashboard serves generated files from disk. On Vercel, a later
    image request may land on a different serverless instance, so files written
    during /api/run are not guaranteed to exist. Data URIs keep the exact same
    visual dashboard while making charts self-contained in the response.
    """

    def replace_png(match: re.Match) -> str:
        prefix, url_path = match.group(1), match.group(2)
        path = _result_file_from_url(url_path)
        if not path.exists():
            return match.group(0)
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        return f'{prefix}"data:image/png;base64,{encoded}"'

    def replace_report(match: re.Match) -> str:
        prefix, url_path = match.group(1), match.group(2)
        path = _result_file_from_url(url_path)
        if not path.exists():
            return match.group(0)
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        return f'{prefix}"data:text/html;base64,{encoded}"'

    html = re.sub(r'(src=)"(/results/[^"]+\.png)"', replace_png, html)
    html = re.sub(r'(href=)"(/results/[^"]+report\.html)"', replace_report, html)
    return html


def _query_dict() -> dict[str, list[str]]:
    """Convert Flask query args into the local dashboard's expected shape."""

    return {key: request.args.getlist(key) for key in request.args.keys()}


def _presentation_flow() -> str:
    """Return the same overview section shown by the local dashboard server."""

    return """
<section>
  <div class="panel-title">
    <div>
      <h2>Presentation Flow</h2>
      <p class="hint">Use this order when explaining the system to your teacher.</p>
    </div>
  </div>
  <div class="mini-grid">
    <div class="feature"><strong>1. Generate Workload</strong> The simulator creates PM capacity, VM CPU/RAM demand, and clustered VM traffic.</div>
    <div class="feature"><strong>2. Run Four Algorithms</strong> FFD, ACS-VMP, Traffic-Aware VMP, and TA-MOACO are compared on the same workload.</div>
    <div class="feature"><strong>3. Explain Tradeoffs</strong> Show how traffic-only placement can lower hops but waste server power.</div>
    <div class="feature"><strong>4. Defend TA-MOACO</strong> TA-MOACO balances consolidation and traffic locality, reducing total energy.</div>
  </div>
</section>
"""


@app.get("/")
def home() -> Response:
    body = controls(_query_dict()) + _presentation_flow()
    return Response(html_page(body), mimetype="text/html")


@app.get("/api/run")
def api_run() -> Response:
    try:
        html = _embed_generated_assets(run_simulation_html(_query_dict()))
        payload = {"ok": True, "html": html}
    except Exception as exc:
        payload = {"ok": False, "error": repr(exc)}
    return Response(json.dumps(payload), mimetype="application/json")


@app.get("/results/<path:relative_path>")
def results_file(relative_path: str) -> Response:
    return send_from_directory(RESULTS_ROOT, relative_path)


@app.get("/api/health")
def health() -> Response:
    return Response(json.dumps({"ok": True, "service": "ta-moaco-local-dashboard"}), mimetype="application/json")


@app.get("/favicon.ico")
def favicon() -> Response:
    return Response("", status=204)
